"""The v1 official first-shot artifact is immutable history: hash-pinned, and
its recorded result (2/3 derived; h03 failed honestly) may never be rewritten
or regenerated by v2 work."""

import hashlib
import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[2]
ARTIFACT = REPO / "docs" / "evidence" / "generalization-first-shot.json"
V1_SHA256 = "3cd075bb544c499523fa11aa7694f22aedbf9ca5fbf413ef131093e59ec553cf"


def test_v1_artifact_bytes_are_pinned():
    assert ARTIFACT.is_file(), "v1 evidence artifact is missing"
    assert hashlib.sha256(ARTIFACT.read_bytes()).hexdigest() == V1_SHA256, (
        "the v1 official first-shot artifact has been modified or regenerated "
        "— it is immutable history")


def test_v1_recorded_result_is_the_honest_two_of_three():
    art = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    assert art["generalization_success"] == "2/3 derived"
    assert art["agent_freeze_commit"] == "8ccbe0d62df1c336e2384d45486db52194630892"
    by_id = {s["scenario"]: s for s in art["scenarios"]}
    assert by_id["h03"]["repair_mode"] == "no_change"
    assert by_id["h03"]["derived_success"] is False
    assert by_id["h03"]["fallback_used"] is False
